-- StalkerMoveset.lua
-- Generated by Reanim Moveset Creator v5
-- Place in: UhhhhhhReanim/Modules/StalkerMoveset.lua
-- Loaded by reanim via: loadstring(data) → func() → AddModules(list)
-- getfenv() injects: AnimLib, ContextActions, AssetGetPathFromFilename,
--   AssetGetContentId, ReanimateFling, ReanimCamera, Util_CreateText,
--   Util_CreateSwitch, Util_CreateSlider, Util_CreateSeparator,
--   SetOverrideMovesetMusic, and more. Do NOT use game:GetService() here.

local modules = {}

local function AddModule(m)
    table.insert(modules, m)
end

AddModule(function()

    -- ── MODULE HEADER ─────────────────────────────────────────────────────
    local m = {}
    m.ModuleType   = "MOVESET"
    m.Name         = "Stalker"
    m.Description  = "It's stalking you"
    m.InternalName = "StalkerMoveset"

    -- ── ASSETS ────────────────────────────────────────────────────────────
    m.Assets = {
        "StalkerIdle.anim",
        "StalkerWalk.anim",
        "StalkerSprint.anim",
        "StalkerM1.anim",
        "StalkerM2.anim",
        "StalkerM3.anim",
        "StalkerRage.anim",
        "StalkerScream.anim",
        "StalkerScream2.anim",
        "StalkerLunge.anim",
        "StalkerStunned.anim",
    }

    -- ── FLING CONFIG ──────────────────────────────────────────────────────
    m.FlingEnabled = {
        ["M1"] = true,
        ["M2"] = true,
        ["M3"] = true,
        ["Rage"] = false,
        ["Scream"] = false,
        ["Scream 2"] = false,
        ["Lunge"] = true,
        ["Stunned"] = false,
    }

    -- ── CONFIG UI (called by reanim to populate the config page) ──────────
    m.Config = function(parent)
        Util_CreateText(parent, "Stalker", 18, Enum.TextXAlignment.Center)
        Util_CreateSeparator(parent)
        Util_CreateText(parent, "Fling on Hit", 15, Enum.TextXAlignment.Center)
        Util_CreateSwitch(parent, "M1 flings", m.FlingEnabled["M1"]).Changed:Connect(function(v) m.FlingEnabled["M1"] = v end)
        Util_CreateSwitch(parent, "M2 flings", m.FlingEnabled["M2"]).Changed:Connect(function(v) m.FlingEnabled["M2"] = v end)
        Util_CreateSwitch(parent, "M3 flings", m.FlingEnabled["M3"]).Changed:Connect(function(v) m.FlingEnabled["M3"] = v end)
        Util_CreateSwitch(parent, "Rage flings", m.FlingEnabled["Rage"]).Changed:Connect(function(v) m.FlingEnabled["Rage"] = v end)
        Util_CreateSwitch(parent, "Scream flings", m.FlingEnabled["Scream"]).Changed:Connect(function(v) m.FlingEnabled["Scream"] = v end)
        Util_CreateSwitch(parent, "Scream 2 flings", m.FlingEnabled["Scream 2"]).Changed:Connect(function(v) m.FlingEnabled["Scream 2"] = v end)
        Util_CreateSwitch(parent, "Lunge flings", m.FlingEnabled["Lunge"]).Changed:Connect(function(v) m.FlingEnabled["Lunge"] = v end)
        Util_CreateSwitch(parent, "Stunned flings", m.FlingEnabled["Stunned"]).Changed:Connect(function(v) m.FlingEnabled["Stunned"] = v end)
    end

    m.SaveConfig = function()
        return { FlingEnabled = m.FlingEnabled }
    end

    m.LoadConfig = function(save)
        if type(save.FlingEnabled) == "table" then
            for k, v in pairs(save.FlingEnabled) do
                if m.FlingEnabled[k] ~= nil then
                    m.FlingEnabled[k] = v
                end
            end
        end
    end

    -- ── LOCAL STATE ────────────────────────────────────────────────────────
    local baseAnims    = {}
    local actionAnims  = {}
    local animJump     = nil
    local actionStart  = {}
    local currentBase   = "idle"
    local currentAction = nil
    local wasInAir      = false
    local flingActive   = false
    local touchConns    = {}
    local allJoints     = {}
    local figureRef     = nil
    local SPEED_WALK    = 16
    local SPEED_SPRINT  = 26
    local isSprinting   = false




    -- ── HELPERS ────────────────────────────────────────────────────────────
    local function makeSound(filename, parent, volume, looped)
        local s = Instance.new("Sound")
        s.SoundId = AssetGetContentId(filename) -- injected global
        s.Volume  = volume or 0.8
        s.Looped  = looped or false
        s.Parent  = parent
        return s
    end

    local function loadAnim(fig, file, looped)
        local a = AnimLib.Animator.new() -- AnimLib is injected global
        a.rig    = fig
        a.track  = AnimLib.Track.fromfile(AssetGetPathFromFilename(file))
        a.looped = looped or false
        a.speed  = 1
        a.weight = 0
        return a
    end

    local function setSpeed(speed)
        if not figureRef then return end
        local hum = figureRef:FindFirstChildOfClass("Humanoid")
        if hum then hum.WalkSpeed = speed end
    end

    local function clearBase()
        for _, a in pairs(baseAnims) do a.weight = 0 end
    end

    local function setBase(state)
        if currentBase == state then return end
        currentBase = state
        clearBase()
        if baseAnims[state] then baseAnims[state].weight = 1 end

    end

    local function stopAllAnimSounds()
        -- (no per-action audio)
    end

    local function stopAction()
        for _, anim in pairs(actionAnims) do anim.weight = 0 end
        stopAllAnimSounds()

        currentAction = nil
        flingActive   = false
    end

    local function playAction(name)
        if currentAction then return end
        local a = actionAnims[name]
        if not a then return end
        stopAction()
        a.weight       = 1
        actionStart[a] = os.clock()
        currentAction  = name
        flingActive    = m.FlingEnabled[name] == true


    end

    local function toggleSprint()
        isSprinting = not isSprinting
        if isSprinting then
            setSpeed(SPEED_SPRINT)
            ContextActions:SetTitle("GM_Sprint", "Walk")
        else
            setSpeed(SPEED_WALK)
            ContextActions:SetTitle("GM_Sprint", "Sprint")
        end
    end

    local function setupFlingTouched(figure)
        local function hookPart(part)
            local conn = part.Touched:Connect(function(hit)
                if not flingActive then return end
                if not hit or not hit.Parent then return end
                local target = hit.Parent
                if target:IsA("Accessory") then target = target.Parent end
                if target == figure then return end
                if not target:FindFirstChildOfClass("Humanoid") then return end
                ReanimateFling(target) -- injected global
            end)
            table.insert(touchConns, conn)
        end
        for _, part in ipairs(figure:GetDescendants()) do
            if part:IsA("BasePart") then hookPart(part) end
        end
        table.insert(touchConns, figure.DescendantAdded:Connect(function(part)
            if part:IsA("BasePart") then hookPart(part) end
        end))
    end


    -- ── INIT ──────────────────────────────────────────────────────────────
    -- figure = reanim's custom character model (not Player.Character)
    m.Init = function(figure)
        figureRef = figure
        local hrp = figure:FindFirstChild("HumanoidRootPart") or figure
        local hum = figure:FindFirstChildOfClass("Humanoid")

        -- Collect Motor6D joints for transform reset on Destroy
        allJoints = {}
        for _, v in ipairs(figure:GetDescendants()) do
            if v:IsA("Motor6D") then table.insert(allJoints, v) end
        end


        -- Base locomotion animations
        baseAnims = {
        idle   = loadAnim(figure, "StalkerIdle.anim", true),
        walk   = loadAnim(figure, "StalkerWalk.anim", true),
        sprint   = loadAnim(figure, "StalkerSprint.anim", true),
        }
        animJump = baseAnims.jump

        -- Attack / ability animations
        actionAnims = {
        ["M1"] = loadAnim(figure, "StalkerM1.anim", false),
        ["M2"] = loadAnim(figure, "StalkerM2.anim", false),
        ["M3"] = loadAnim(figure, "StalkerM3.anim", false),
        ["Rage"] = loadAnim(figure, "StalkerRage.anim", false),
        ["Scream"] = loadAnim(figure, "StalkerScream.anim", false),
        ["Scream 2"] = loadAnim(figure, "StalkerScream2.anim", false),
        ["Lunge"] = loadAnim(figure, "StalkerLunge.anim", false),
        ["Stunned"] = loadAnim(figure, "StalkerStunned.anim", false),
        }




        setSpeed(SPEED_WALK)
        setBase("idle")
        setupFlingTouched(figure)

        -- ContextActions: reanim's custom object (injected via getfenv, NOT game:GetService)
        -- SetPosition is relative to reanim's buttonsui frame near the Roblox jump button
        ContextActions:BindAction("GM_Sprint", function(_, inputState, _)
            if inputState == Enum.UserInputState.Begin then toggleSprint() end
        end, true, Enum.KeyCode.LeftAlt)
        ContextActions:SetTitle("GM_Sprint", "Sprint")
        ContextActions:SetPosition("GM_Sprint", UDim2.new(1, -260, 1, -130))

        ContextActions:BindAction("GM_M1", function(_, inputState, _)
            if inputState == Enum.UserInputState.Begin then playAction("M1") end
        end, true, Enum.KeyCode.Z)
        ContextActions:SetTitle("GM_M1", "M1")
        ContextActions:SetPosition("GM_M1", UDim2.new(1, -230, 1, -130))

        ContextActions:BindAction("GM_M2", function(_, inputState, _)
            if inputState == Enum.UserInputState.Begin then playAction("M2") end
        end, true, Enum.KeyCode.X)
        ContextActions:SetTitle("GM_M2", "M2")
        ContextActions:SetPosition("GM_M2", UDim2.new(1, -180, 1, -130))

        ContextActions:BindAction("GM_M3", function(_, inputState, _)
            if inputState == Enum.UserInputState.Begin then playAction("M3") end
        end, true, Enum.KeyCode.C)
        ContextActions:SetTitle("GM_M3", "M3")
        ContextActions:SetPosition("GM_M3", UDim2.new(1, -130, 1, -130))

        ContextActions:BindAction("GM_Rage", function(_, inputState, _)
            if inputState == Enum.UserInputState.Begin then playAction("Rage") end
        end, true, Enum.KeyCode.Z)
        ContextActions:SetTitle("GM_Rage", "Rage")
        ContextActions:SetPosition("GM_Rage", UDim2.new(1, -230, 1, -80))

        ContextActions:BindAction("GM_Scream", function(_, inputState, _)
            if inputState == Enum.UserInputState.Begin then playAction("Scream") end
        end, true, Enum.KeyCode.Z)
        ContextActions:SetTitle("GM_Scream", "Scream")
        ContextActions:SetPosition("GM_Scream", UDim2.new(1, -180, 1, -80))

        ContextActions:BindAction("GM_Scream 2", function(_, inputState, _)
            if inputState == Enum.UserInputState.Begin then playAction("Scream 2") end
        end, true, Enum.KeyCode.Z)
        ContextActions:SetTitle("GM_Scream 2", "Scream 2")
        ContextActions:SetPosition("GM_Scream 2", UDim2.new(1, -130, 1, -80))

        ContextActions:BindAction("GM_Lunge", function(_, inputState, _)
            if inputState == Enum.UserInputState.Begin then playAction("Lunge") end
        end, true, Enum.KeyCode.Z)
        ContextActions:SetTitle("GM_Lunge", "Lunge")
        ContextActions:SetPosition("GM_Lunge", UDim2.new(1, -230, 1, -60))

        ContextActions:BindAction("GM_Stunned", function(_, inputState, _)
            if inputState == Enum.UserInputState.Begin then playAction("Stunned") end
        end, true, Enum.KeyCode.Z)
        ContextActions:SetTitle("GM_Stunned", "Stunned")
        ContextActions:SetPosition("GM_Stunned", UDim2.new(1, -190, 1, -45))
    end

    -- ── UPDATE ─────────────────────────────────────────────────────────────
    -- Called every Heartbeat by reanim (inside xpcall — errors won't crash)
    m.Update = function(dt, figure)
        local hum = figure:FindFirstChildOfClass("Humanoid")
        if not hum then return end
        local inAir = hum.FloorMaterial == Enum.Material.Air

        -- Auto-stop action when duration elapsed
        if currentAction then
            local a = actionAnims[currentAction]
            if a and actionStart[a] then
                local elapsed  = os.clock() - actionStart[a]
                local duration = a.track and a.track.Time or 0
                if duration > 0 and elapsed >= duration / (a.speed or 1) then
                    a.weight      = 0
                    stopAllAnimSounds()

                    currentAction = nil
                    flingActive   = false
                    currentBase   = "none"
                end
            end
        end

        -- Base locomotion state machine
        if not currentAction then
            if inAir then
                if not wasInAir then
                    clearBase()
                    currentBase           = "jump"
                    animJump.weight       = 1
                    actionStart[animJump] = os.clock()
                end
            else
                if wasInAir then animJump.weight = 0 end
                local moving = hum.MoveDirection.Magnitude > 0.1
                if moving then
                    if isSprinting then setBase("sprint") else setBase("walk") end
                else
                    setBase("idle")
                end
            end
        end

        wasInAir = inAir

        -- Step all active animators
        local now = os.clock()
        for _, a in pairs(baseAnims) do
            if a.weight > 0 then a:Step(now) end
        end
        for a, start in pairs(actionStart) do
            if a.weight > 0 then a:Step(now - start) end
        end
    end

    -- ── DESTROY ─────────────────────────────────────────────────────────────
    -- Called when moveset is deactivated or switched.
    -- CRITICAL: Reset all Motor6D transforms to prevent animation bleed.
    m.Destroy = function()
        -- Unbind all ContextActions buttons
        ContextActions:UnbindAction("GM_Sprint")
        ContextActions:UnbindAction("GM_M1")
        ContextActions:UnbindAction("GM_M2")
        ContextActions:UnbindAction("GM_M3")
        ContextActions:UnbindAction("GM_Rage")
        ContextActions:UnbindAction("GM_Scream")
        ContextActions:UnbindAction("GM_Scream 2")
        ContextActions:UnbindAction("GM_Lunge")
        ContextActions:UnbindAction("GM_Stunned")

        -- Disconnect fling touch connections
        for _, conn in ipairs(touchConns) do conn:Disconnect() end
        table.clear(touchConns)

        stopAllAnimSounds()



        -- Reset Motor6D transforms — prevents animation bleed into next moveset
        for _, joint in ipairs(allJoints) do
            if joint and joint.Parent then
                joint.Transform = CFrame.identity
            end
        end
        allJoints = {}

        -- Zero all anim weights so AnimLib stops driving transforms
        for _, a in pairs(baseAnims)   do a.weight = 0 end
        for _, a in pairs(actionAnims) do a.weight = 0 end

        setSpeed(16)

        actionStart   = {}
        currentAction = nil
        currentBase   = "idle"
        wasInAir      = false
        flingActive   = false
        figureRef     = nil
        animJump      = nil
        baseAnims     = {}
        actionAnims   = {}
        isSprinting = false
    end

    return m
end)

return modules
