-- MissCircleMoveset.lua
-- Generated by Reanim Moveset Creator v5
-- Place in: UhhhhhhReanim/Modules/MissCircleMoveset.lua
-- Loaded by reanim via: loadstring(data) → func() → AddModules(list)
-- getfenv() injects: AnimLib, ContextActions, AssetGetPathFromFilename,
--   AssetGetContentId, ReanimateFling, ReanimCamera, Util_CreateText,
--   Util_CreateSwitch, Util_CreateSlider, Util_CreateSeparator,
--   SetOverrideMovesetMusic, and more. Do NOT use game:GetService() here.

local modules = {}

local function AddModule(m)
    table.insert(modules, m)
end

AddModule(function()

    -- ── MODULE HEADER ─────────────────────────────────────────────────────
    local m = {}
    m.ModuleType   = "MOVESET"
    m.Name         = "Miss Circle Moveset"
    m.Description  = "\"Zip, Oliver, What are you doing?.\""
    m.InternalName = "MissCircleMoveset"

    -- ── ASSETS ────────────────────────────────────────────────────────────
    m.Assets = {
        "MissCircleIdle.anim",
        "MissCircleWalk.anim",
        "MissCircleRun.anim",
        "MissCircleJump.anim",
        "MissCircleSwing.anim",
        "MissCircleBlock.anim",
        "MissCircleFailure.anim",
        "FailuresTheme.mp3",
        "MissCirclewalk.mp3",
        "MissCircleRun.mp3",
        "MissCircleSwing.mp3",
        "MissCircleBlock.mp3",
        "MissCircleFailure.mp3",
    }

    -- ── FLING CONFIG ──────────────────────────────────────────────────────
    m.FlingEnabled = {
        ["Swing"] = true,
        ["Block"] = false,
        ["Failure"] = false,
    }

    -- ── CONFIG UI (called by reanim to populate the config page) ──────────
    m.Config = function(parent)
        Util_CreateText(parent, "Miss Circle Moveset", 18, Enum.TextXAlignment.Center)
        Util_CreateSeparator(parent)
        Util_CreateText(parent, "Fling on Hit", 15, Enum.TextXAlignment.Center)
        Util_CreateSwitch(parent, "Swing flings", m.FlingEnabled["Swing"]).Changed:Connect(function(v) m.FlingEnabled["Swing"] = v end)
        Util_CreateSwitch(parent, "Block flings", m.FlingEnabled["Block"]).Changed:Connect(function(v) m.FlingEnabled["Block"] = v end)
        Util_CreateSwitch(parent, "Failure flings", m.FlingEnabled["Failure"]).Changed:Connect(function(v) m.FlingEnabled["Failure"] = v end)
    end

    m.SaveConfig = function()
        return { FlingEnabled = m.FlingEnabled }
    end

    m.LoadConfig = function(save)
        if type(save.FlingEnabled) == "table" then
            for k, v in pairs(save.FlingEnabled) do
                if m.FlingEnabled[k] ~= nil then
                    m.FlingEnabled[k] = v
                end
            end
        end
    end

    -- ── LOCAL STATE ────────────────────────────────────────────────────────
    local baseAnims    = {}
    local actionAnims  = {}
    local animJump     = nil
    local actionStart  = {}
    local currentBase   = "idle"
    local currentAction = nil
    local wasInAir      = false
    local flingActive   = false
    local touchConns    = {}
    local allJoints     = {}
    local figureRef     = nil
    local SPEED_WALK    = 4
    local SPEED_SPRINT  = 26
    local isSprinting   = false
    local bgSound = nil

    -- Per-animation loop sounds (play/stop per state)
    local animSnd_MissCircleWalk_anim = nil
    local animSnd_MissCircleRun_anim = nil
    local animSnd_Swing = nil
    local animSnd_Block = nil
    local animSnd_Failure = nil


    -- ── HELPERS ────────────────────────────────────────────────────────────
    local function makeSound(filename, parent, volume, looped)
        local s = Instance.new("Sound")
        s.SoundId = AssetGetContentId(filename) -- injected global
        s.Volume  = volume or 0.8
        s.Looped  = looped or false
        s.Parent  = parent
        return s
    end

    local function loadAnim(fig, file, looped)
        local a = AnimLib.Animator.new() -- AnimLib is injected global
        a.rig    = fig
        a.track  = AnimLib.Track.fromfile(AssetGetPathFromFilename(file))
        a.looped = looped or false
        a.speed  = 1
        a.weight = 0
        return a
    end

    local function setSpeed(speed)
        if not figureRef then return end
        local hum = figureRef:FindFirstChildOfClass("Humanoid")
        if hum then hum.WalkSpeed = speed end
    end

    local function clearBase()
        for _, a in pairs(baseAnims) do a.weight = 0 end
    end

    local function setBase(state)
        if currentBase == state then return end
        currentBase = state
        clearBase()
        if baseAnims[state] then baseAnims[state].weight = 1 end
        -- Per-base-anim loop audio
        if state == "walk" then
            if animSnd_walk and not animSnd_walk.IsPlaying then animSnd_walk:Play() end
        else
            if animSnd_walk then animSnd_walk:Stop() end
        end
        if state == "sprint" then
            if animSnd_sprint and not animSnd_sprint.IsPlaying then animSnd_sprint:Play() end
        else
            if animSnd_sprint then animSnd_sprint:Stop() end
        end
    end

    local function stopAllAnimSounds()
        if animSnd_Swing then animSnd_Swing:Stop() end
        if animSnd_Block then animSnd_Block:Stop() end
        if animSnd_Failure then animSnd_Failure:Stop() end
    end

    local function stopAction()
        for _, anim in pairs(actionAnims) do anim.weight = 0 end
        stopAllAnimSounds()

        currentAction = nil
        flingActive   = false
    end

    local function playAction(name)
        if currentAction then return end
        local a = actionAnims[name]
        if not a then return end
        stopAction()
        a.weight       = 1
        actionStart[a] = os.clock()
        currentAction  = name
        flingActive    = m.FlingEnabled[name] == true
        -- Per-action audio
        if name == "Swing" and animSnd_Swing then animSnd_Swing:Play() end
        if name == "Block" and animSnd_Block then animSnd_Block:Play() end
        if name == "Failure" and animSnd_Failure then animSnd_Failure:Play() end

    end

    local function toggleSprint()
        isSprinting = not isSprinting
        if isSprinting then
            setSpeed(SPEED_SPRINT)
            ContextActions:SetTitle("GM_Sprint", "Walk")
        else
            setSpeed(SPEED_WALK)
            ContextActions:SetTitle("GM_Sprint", "Sprint")
        end
    end

    local function setupFlingTouched(figure)
        local function hookPart(part)
            local conn = part.Touched:Connect(function(hit)
                if not flingActive then return end
                if not hit or not hit.Parent then return end
                local target = hit.Parent
                if target:IsA("Accessory") then target = target.Parent end
                if target == figure then return end
                if not target:FindFirstChildOfClass("Humanoid") then return end
                ReanimateFling(target) -- injected global
            end)
            table.insert(touchConns, conn)
        end
        for _, part in ipairs(figure:GetDescendants()) do
            if part:IsA("BasePart") then hookPart(part) end
        end
        table.insert(touchConns, figure.DescendantAdded:Connect(function(part)
            if part:IsA("BasePart") then hookPart(part) end
        end))
    end


    -- ── INIT ──────────────────────────────────────────────────────────────
    -- figure = reanim's custom character model (not Player.Character)
    m.Init = function(figure)
        figureRef = figure
        local hrp = figure:FindFirstChild("HumanoidRootPart") or figure
        local hum = figure:FindFirstChildOfClass("Humanoid")

        -- Collect Motor6D joints for transform reset on Destroy
        allJoints = {}
        for _, v in ipairs(figure:GetDescendants()) do
            if v:IsA("Motor6D") then table.insert(allJoints, v) end
        end


        -- Base locomotion animations
        baseAnims = {
        idle   = loadAnim(figure, "MissCircleIdle.anim", true),
        walk   = loadAnim(figure, "MissCircleWalk.anim", true),
        sprint   = loadAnim(figure, "MissCircleRun.anim", true),
        jump   = loadAnim(figure, "MissCircleJump.anim", true),
        }
        animJump = baseAnims.jump

        -- Attack / ability animations
        actionAnims = {
        ["Swing"] = loadAnim(figure, "MissCircleSwing.anim", false),
        ["Block"] = loadAnim(figure, "MissCircleBlock.anim", false),
        ["Failure"] = loadAnim(figure, "MissCircleFailure.anim", false),
        }

        -- Persistent background sound
        bgSound = makeSound("FailuresTheme.mp3", hrp, 0.5, true)
        bgSound:Play()

        -- Init per-animation audio
    animSnd_MissCircleWalk_anim = makeSound("MissCirclewalk.mp3", hrp, 0.7, false)
    animSnd_MissCircleRun_anim = makeSound("MissCircleRun.mp3", hrp, 0.8, false)
    animSnd_Swing = makeSound("MissCircleSwing.mp3", hrp, 0.8, false)
    animSnd_Block = makeSound("MissCircleBlock.mp3", hrp, 0.8, false)
    animSnd_Failure = makeSound("MissCircleFailure.mp3", hrp, 0.9, false)


        setSpeed(SPEED_WALK)
        setBase("idle")
        setupFlingTouched(figure)

        -- ContextActions: reanim's custom object (injected via getfenv, NOT game:GetService)
        -- SetPosition is relative to reanim's buttonsui frame near the Roblox jump button
        ContextActions:BindAction("GM_Sprint", function(_, inputState, _)
            if inputState == Enum.UserInputState.Begin then toggleSprint() end
        end, true, Enum.KeyCode.LeftAlt)
        ContextActions:SetTitle("GM_Sprint", "Sprint")
        ContextActions:SetPosition("GM_Sprint", UDim2.new(1, -260, 1, -130))

        ContextActions:BindAction("GM_Swing", function(_, inputState, _)
            if inputState == Enum.UserInputState.Begin then playAction("Swing") end
        end, true, Enum.KeyCode.Z)
        ContextActions:SetTitle("GM_Swing", "Swing")
        ContextActions:SetPosition("GM_Swing", UDim2.new(1, -230, 1, -130))

        ContextActions:BindAction("GM_Block", function(_, inputState, _)
            if inputState == Enum.UserInputState.Begin then playAction("Block") end
        end, true, Enum.KeyCode.X)
        ContextActions:SetTitle("GM_Block", "Block")
        ContextActions:SetPosition("GM_Block", UDim2.new(1, -180, 1, -130))

        ContextActions:BindAction("GM_Failure", function(_, inputState, _)
            if inputState == Enum.UserInputState.Begin then playAction("Failure") end
        end, true, Enum.KeyCode.C)
        ContextActions:SetTitle("GM_Failure", "Failure")
        ContextActions:SetPosition("GM_Failure", UDim2.new(1, -130, 1, -130))
    end

    -- ── UPDATE ─────────────────────────────────────────────────────────────
    -- Called every Heartbeat by reanim (inside xpcall — errors won't crash)
    m.Update = function(dt, figure)
        local hum = figure:FindFirstChildOfClass("Humanoid")
        if not hum then return end
        local inAir = hum.FloorMaterial == Enum.Material.Air

        -- Auto-stop action when duration elapsed
        if currentAction then
            local a = actionAnims[currentAction]
            if a and actionStart[a] then
                local elapsed  = os.clock() - actionStart[a]
                local duration = a.track and a.track.Time or 0
                if duration > 0 and elapsed >= duration / (a.speed or 1) then
                    a.weight      = 0
                    stopAllAnimSounds()

                    currentAction = nil
                    flingActive   = false
                    currentBase   = "none"
                end
            end
        end

        -- Base locomotion state machine
        if not currentAction then
            if inAir then
                if not wasInAir then
                    clearBase()
                    currentBase           = "jump"
                    animJump.weight       = 1
                    actionStart[animJump] = os.clock()
                end
            else
                if wasInAir then animJump.weight = 0 end
                local moving = hum.MoveDirection.Magnitude > 0.1
                if moving then
                    if isSprinting then setBase("sprint") else setBase("walk") end
                else
                    setBase("idle")
                end
            end
        end

        wasInAir = inAir

        -- Step all active animators
        local now = os.clock()
        for _, a in pairs(baseAnims) do
            if a.weight > 0 then a:Step(now) end
        end
        for a, start in pairs(actionStart) do
            if a.weight > 0 then a:Step(now - start) end
        end
    end

    -- ── DESTROY ─────────────────────────────────────────────────────────────
    -- Called when moveset is deactivated or switched.
    -- CRITICAL: Reset all Motor6D transforms to prevent animation bleed.
    m.Destroy = function()
        -- Unbind all ContextActions buttons
        ContextActions:UnbindAction("GM_Sprint")
        ContextActions:UnbindAction("GM_Swing")
        ContextActions:UnbindAction("GM_Block")
        ContextActions:UnbindAction("GM_Failure")

        -- Disconnect fling touch connections
        for _, conn in ipairs(touchConns) do conn:Disconnect() end
        table.clear(touchConns)

        if bgSound then bgSound:Stop() bgSound:Destroy() bgSound = nil end
        stopAllAnimSounds()

    if animSnd_MissCircleWalk_anim then animSnd_MissCircleWalk_anim:Stop() animSnd_MissCircleWalk_anim:Destroy() animSnd_MissCircleWalk_anim = nil end
    if animSnd_MissCircleRun_anim then animSnd_MissCircleRun_anim:Stop() animSnd_MissCircleRun_anim:Destroy() animSnd_MissCircleRun_anim = nil end
    if animSnd_Swing then animSnd_Swing:Stop() animSnd_Swing:Destroy() animSnd_Swing = nil end
    if animSnd_Block then animSnd_Block:Stop() animSnd_Block:Destroy() animSnd_Block = nil end
    if animSnd_Failure then animSnd_Failure:Stop() animSnd_Failure:Destroy() animSnd_Failure = nil end



        -- Reset Motor6D transforms — prevents animation bleed into next moveset
        for _, joint in ipairs(allJoints) do
            if joint and joint.Parent then
                joint.Transform = CFrame.identity
            end
        end
        allJoints = {}

        -- Zero all anim weights so AnimLib stops driving transforms
        for _, a in pairs(baseAnims)   do a.weight = 0 end
        for _, a in pairs(actionAnims) do a.weight = 0 end

        setSpeed(16)

        actionStart   = {}
        currentAction = nil
        currentBase   = "idle"
        wasInAir      = false
        flingActive   = false
        figureRef     = nil
        animJump      = nil
        baseAnims     = {}
        actionAnims   = {}
        isSprinting = false
    end

    return m
end)

return modules
