-- PwnedBy1400Module.lua
-- Generated by Reanim Moveset Creator v5
-- Place in: UhhhhhhReanim/Modules/PwnedBy1400Module.lua
-- Loaded by reanim via: loadstring(data) → func() → AddModules(list)
-- getfenv() injects: AnimLib, ContextActions, AssetGetPathFromFilename,
--   AssetGetContentId, ReanimateFling, ReanimCamera, Util_CreateText,
--   Util_CreateSwitch, Util_CreateSlider, Util_CreateSeparator,
--   SetOverrideMovesetMusic, and more. Do NOT use game:GetService() here.

local modules = {}

local function AddModule(m)
    table.insert(modules, m)
end

AddModule(function()

    -- ── MODULE HEADER ─────────────────────────────────────────────────────
    local m = {}
    m.ModuleType   = "MOVESET"
    m.Name         = "Pwned By 14:00 Moveset"
    m.Description  = "Just the normal anims"
    m.InternalName = "PwnedBy1400Module"

    -- ── ASSETS ────────────────────────────────────────────────────────────
    m.Assets = {
        "PwnedIdle.anim",
        "PwnedWalk.anim",
        "PwnedRun.anim",
        "PwnedJump.anim",
    }

    -- ── FLING CONFIG ──────────────────────────────────────────────────────
    m.FlingEnabled = {
        -- no action anims
    }

    -- ── CONFIG UI (called by reanim to populate the config page) ──────────
    m.Config = function(parent)
        Util_CreateText(parent, "Pwned By 14:00 Moveset", 18, Enum.TextXAlignment.Center)
        Util_CreateSeparator(parent)
        Util_CreateText(parent, "Fling on Hit", 15, Enum.TextXAlignment.Center)
        -- no action anims
    end

    m.SaveConfig = function()
        return { FlingEnabled = m.FlingEnabled }
    end

    m.LoadConfig = function(save)
        if type(save.FlingEnabled) == "table" then
            for k, v in pairs(save.FlingEnabled) do
                if m.FlingEnabled[k] ~= nil then
                    m.FlingEnabled[k] = v
                end
            end
        end
    end

    -- ── LOCAL STATE ────────────────────────────────────────────────────────
    local baseAnims    = {}
    local actionAnims  = {}
    local animJump     = nil
    local actionStart  = {}
    local currentBase   = "idle"
    local currentAction = nil
    local wasInAir      = false
    local flingActive   = false
    local touchConns    = {}
    local allJoints     = {}
    local figureRef     = nil
    local SPEED_WALK    = 15
    local SPEED_SPRINT  = 30
    local isSprinting   = false




    -- ── HELPERS ────────────────────────────────────────────────────────────
    local function makeSound(filename, parent, volume, looped)
        local s = Instance.new("Sound")
        s.SoundId = AssetGetContentId(filename) -- injected global
        s.Volume  = volume or 0.8
        s.Looped  = looped or false
        s.Parent  = parent
        return s
    end

    local function loadAnim(fig, file, looped)
        local a = AnimLib.Animator.new() -- AnimLib is injected global
        a.rig    = fig
        a.track  = AnimLib.Track.fromfile(AssetGetPathFromFilename(file))
        a.looped = looped or false
        a.speed  = 1
        a.weight = 0
        return a
    end

    local function setSpeed(speed)
        if not figureRef then return end
        local hum = figureRef:FindFirstChildOfClass("Humanoid")
        if hum then hum.WalkSpeed = speed end
    end

    local function clearBase()
        for _, a in pairs(baseAnims) do a.weight = 0 end
    end

    local function setBase(state)
        if currentBase == state then return end
        currentBase = state
        clearBase()
        if baseAnims[state] then baseAnims[state].weight = 1 end

    end

    local function stopAllAnimSounds()
        -- (no per-action audio)
    end

    local function stopAction()
        for _, anim in pairs(actionAnims) do anim.weight = 0 end
        stopAllAnimSounds()

        currentAction = nil
        flingActive   = false
    end

    local function playAction(name)
        if currentAction then return end
        local a = actionAnims[name]
        if not a then return end
        stopAction()
        a.weight       = 1
        actionStart[a] = os.clock()
        currentAction  = name
        flingActive    = m.FlingEnabled[name] == true


    end

    local function toggleSprint()
        isSprinting = not isSprinting
        if isSprinting then
            setSpeed(SPEED_SPRINT)
            ContextActions:SetTitle("GM_Sprint", "Walk")
        else
            setSpeed(SPEED_WALK)
            ContextActions:SetTitle("GM_Sprint", "Sprint")
        end
    end

    local function setupFlingTouched(figure)
        local function hookPart(part)
            local conn = part.Touched:Connect(function(hit)
                if not flingActive then return end
                if not hit or not hit.Parent then return end
                local target = hit.Parent
                if target:IsA("Accessory") then target = target.Parent end
                if target == figure then return end
                if not target:FindFirstChildOfClass("Humanoid") then return end
                ReanimateFling(target) -- injected global
            end)
            table.insert(touchConns, conn)
        end
        for _, part in ipairs(figure:GetDescendants()) do
            if part:IsA("BasePart") then hookPart(part) end
        end
        table.insert(touchConns, figure.DescendantAdded:Connect(function(part)
            if part:IsA("BasePart") then hookPart(part) end
        end))
    end


    -- ── INIT ──────────────────────────────────────────────────────────────
    -- figure = reanim's custom character model (not Player.Character)
    m.Init = function(figure)
        figureRef = figure
        local hrp = figure:FindFirstChild("HumanoidRootPart") or figure
        local hum = figure:FindFirstChildOfClass("Humanoid")

        -- Collect Motor6D joints for transform reset on Destroy
        allJoints = {}
        for _, v in ipairs(figure:GetDescendants()) do
            if v:IsA("Motor6D") then table.insert(allJoints, v) end
        end


        -- Base locomotion animations
        baseAnims = {
        idle   = loadAnim(figure, "PwnedIdle.anim", true),
        walk   = loadAnim(figure, "PwnedWalk.anim", true),
        sprint   = loadAnim(figure, "PwnedRun.anim", true),
        jump   = loadAnim(figure, "PwnedJump.anim", true),
        }
        animJump = baseAnims.jump





        setSpeed(SPEED_WALK)
        setBase("idle")
        setupFlingTouched(figure)

        -- ContextActions: reanim's custom object (injected via getfenv, NOT game:GetService)
        -- SetPosition is relative to reanim's buttonsui frame near the Roblox jump button
        ContextActions:BindAction("GM_Sprint", function(_, inputState, _)
            if inputState == Enum.UserInputState.Begin then toggleSprint() end
        end, true, Enum.KeyCode.LeftAlt)
        ContextActions:SetTitle("GM_Sprint", "Sprint")
        ContextActions:SetPosition("GM_Sprint", UDim2.new(1, -260, 1, -130))
        -- (no attack buttons)
    end

    -- ── UPDATE ─────────────────────────────────────────────────────────────
    -- Called every Heartbeat by reanim (inside xpcall — errors won't crash)
    m.Update = function(dt, figure)
        local hum = figure:FindFirstChildOfClass("Humanoid")
        if not hum then return end
        local inAir = hum.FloorMaterial == Enum.Material.Air

        -- Auto-stop action when duration elapsed
        if currentAction then
            local a = actionAnims[currentAction]
            if a and actionStart[a] then
                local elapsed  = os.clock() - actionStart[a]
                local duration = a.track and a.track.Time or 0
                if duration > 0 and elapsed >= duration / (a.speed or 1) then
                    a.weight      = 0
                    stopAllAnimSounds()

                    currentAction = nil
                    flingActive   = false
                    currentBase   = "none"
                end
            end
        end

        -- Base locomotion state machine
        if not currentAction then
            if inAir then
                if not wasInAir then
                    clearBase()
                    currentBase           = "jump"
                    animJump.weight       = 1
                    actionStart[animJump] = os.clock()
                end
            else
                if wasInAir then animJump.weight = 0 end
                local moving = hum.MoveDirection.Magnitude > 0.1
                if moving then
                    if isSprinting then setBase("sprint") else setBase("walk") end
                else
                    setBase("idle")
                end
            end
        end

        wasInAir = inAir

        -- Step all active animators
        local now = os.clock()
        for _, a in pairs(baseAnims) do
            if a.weight > 0 then a:Step(now) end
        end
        for a, start in pairs(actionStart) do
            if a.weight > 0 then a:Step(now - start) end
        end
    end

    -- ── DESTROY ─────────────────────────────────────────────────────────────
    -- Called when moveset is deactivated or switched.
    -- CRITICAL: Reset all Motor6D transforms to prevent animation bleed.
    m.Destroy = function()
        -- Unbind all ContextActions buttons
        ContextActions:UnbindAction("GM_Sprint")
        -- (no attack buttons to unbind)

        -- Disconnect fling touch connections
        for _, conn in ipairs(touchConns) do conn:Disconnect() end
        table.clear(touchConns)

        stopAllAnimSounds()



        -- Reset Motor6D transforms — prevents animation bleed into next moveset
        for _, joint in ipairs(allJoints) do
            if joint and joint.Parent then
                joint.Transform = CFrame.identity
            end
        end
        allJoints = {}

        -- Zero all anim weights so AnimLib stops driving transforms
        for _, a in pairs(baseAnims)   do a.weight = 0 end
        for _, a in pairs(actionAnims) do a.weight = 0 end

        setSpeed(16)

        actionStart   = {}
        currentAction = nil
        currentBase   = "idle"
        wasInAir      = false
        flingActive   = false
        figureRef     = nil
        animJump      = nil
        baseAnims     = {}
        actionAnims   = {}
        isSprinting = false
    end

    return m
end)

return modules
